### ISSUE TITLE
ValueError: could not broadcast input array from shape (7,227,227,1) into shape (10,227,227,1)

### ISSUE THREAD

**Issue by Akashpanchal95** [tnybny/Frame-level-anomalies-in-videos#2]
Hello tnybny, Thanks for your code of abnormal video detection. when I use your code to train STAE model I got this error
  File ..\src\data_iterator.py", line 48, in get_test_batch
    batch[i] = self.test[self._index:(self._index + TVOL)]
ValueError: could not broadcast input array from shape (7,227,227,1) into shape (10,227,227,1)

**Comment by tnybny** [comment]
I can train the STAE model just fine. Are you using a different dataset?

**Comment by Akashpanchal95** [comment]
No, I have used the same dataset.

**Comment by tnybny** [comment]
Then I need more information. Did you use the create_datasets.py script to create the training and testing sets? At what iteration do you get this error?

**Comment by Akashpanchal95** [comment]
Hello, @tnybny 
I had tried again to create a model using STAE. Now I am successful to build STAE model. I had suffered only one problem to create model because I had use python3 and so I change line 55 from train.py to line 56 changes as shown below
`line 55 #per_frame_average_error = np.asarray(map(lambda x: np.mean(x), per_frame_error))
 line 56  per_frame_average_error = np.fromiter(map(lambda x: np.mean(x), per_frame_error),dtype=int)`

Thanks

**Comment by tnybny** [comment]
Thanks for letting me know!

**Comment by tiffany-mgx** [comment]
Hello @tnybny @Akashpanchal95 
I also have this problem, when create the STAE. I had use python3.5.0 and changed line 55 from train.py to line 56. but the problem still remains.Error shown below
    **batch[i] = self.test[int(self._index):(int(self._index) + int(self._tvol))]
ValueError: could not broadcast input array from shape (8,227,227,1) into shape (10,227,227,1)
Error in "data_iterator.py" file.**

Do you have any suggestions?

**Comment by tnybny** [comment]
Doesn't look like you're on the latest commit of the repo. Recently I've switched to using a tf.data pipeline.

**Comment by tiffany-mgx** [comment]
Thank you Tnybny, I have solve this problem by change the python version to 2.7.but there is another problem when I trained model 'STAE'.   model  'CONVAE2D' and 'EXP'  are working properly!
**AttributeError: 'DType' object has no attribute 'type'**
Thanks for your time
