### ISSUE TITLE
Visualizing predictions

### ISSUE THREAD

**Issue by benjiebob** [tnybny/Frame-level-anomalies-in-videos#3]
Hi there,

I have just downloaded your code and things seem to be training OK. I wonder if you already have a method for visualizing the predictions? The graphs are great, but it would be nice to see what's going on by generating a new video (or directory of frames) with abnormalities marked.

Thanks,

Ben

**Comment by tnybny** [comment]
@benjiebob My apologies for the delayed response. I think you're referring to visualization of the localization of anomalies. Neither of the papers here claim to perform localization - in fact, they perform very poorly on the localization task. Here's some pseudocode to get you started on it, which I will not be adding to the repo:
```
from src.conv_AE_2D import ConvAE2d
from src.data_iterator import DataIterator
import matplotlib.pyplot
import numpy as np

data = DataIterator(...)
net = ConvAE2d(tvol=TVOL, alpha=ALPHA, batch_size=BATCH_SIZE)
net.restore_model(model_path)
x = data.get_train_batch()
x_ = net.batch_reconstruct(x)
pixel_errs = np.square(x - x_)
NUM_CLIPS = 8

matplotlib.pyplot.figure()
f, axarr = matplotlib.pyplot.subplots(NUM_CLIPS * 2, TVOL, figsize = (20,120))
for i in xrange(NUM_CLIPS * 2):
    if i % 2 == 0:
            clip_id = np.random.randint(0, BATCH_SIZE)
    for j in xrange(TVOL):
        if i % 2 == 0:
            axarr[i, j].imshow(np.squeeze(x[clip_id, :, :, j]), cmap='gray')
        else:
            axarr[i, j].imshow(np.squeeze(pixel_errs[clip_id, :, :, j]), cmap='gray')
        axarr[i, j].axis('off')
```

Let me know if you have any trouble.
