### ISSUE TITLE
No module named compute_frame_roc_auc

### ISSUE THREAD

**Issue by Abudhagir** [tnybny/Frame-level-anomalies-in-videos#4]
Hi BharathKumar,
I am trying to execute ur code. I think some files are not available in ur repo and getting following 
errors.

1. from src.evaluation.compute_frame_roc_auc import compute_frame_roc_auc
2.  from src.plots import plot_loss, plot_auc, plot_pfe
ImportError: No module named src.plots

Can you help me out from this issue.

**Comment by Abudhagir** [comment]
Hi tnybny,

Can you me help me out these issues.

1. from src.evaluation.compute_frame_roc_auc import compute_frame_roc_auc
   ModuleNotFoundError: 
               No module named src.evaluation.compute_frame_roc_auc'

2. While run main.py, 
   gt_trackfile = glob(os.path.join(test_dirs[i], '*_gt.txt')) [0]
 IndexError: list index out of range

**Comment by tnybny** [comment]
I've pushed what should be a fix, could you check now?

**Comment by youngupup** [comment]
@Abudhagir  could you give me the code of the frame of compute_frame_roc_auc？
