### ISSUE TITLE
When running python create_streetscene_frame_annotation.py

### ISSUE THREAD

**Issue by st186** [tnybny/Frame-level-anomalies-in-videos#8]
Traceback (most recent call last):
  File "create_streetscene_frame_annotation.py", line 15, in <module>
    gt_trackfile = glob(os.path.join(test_dirs[i], '*_gt.txt'))[0]
IndexError: list index out of range

**Comment by tnybny** [comment]
Street Scene is not publicly available yet, ignore this file.
