### ISSUE TITLE
evaluation directory is empty

### ISSUE THREAD

**Issue by siamak-p** [tnybny/Frame-level-anomalies-in-videos#9]

**Comment by siamak-p** [comment]
dear tnybny your evaluation directory is empty from modules

**Comment by tnybny** [comment]
src/evaluation directory is empty on purpose, there are two functions (compute_frame_roc_auc and compute_pixel_roc_auc) I've left for readers to implement from reference [1] in the Readme. 
The code should run just fine with an alternate frame-level AUC calculator.
